webserver: caddy
app_dll: DotnetApp.dll
root_path: /var/www/app1
update_zip_absolute_path: /home/ubuntu/DotnetApp.zip
caddy_upstream_key: dotnetcore
healthcheck: /test
shared_files:
  - appsettings.Production.json
servers:
  - port: 5150
    path: /var/www/app1/app_5150
  - port: 5151
    path: /var/www/app1/app_5151
